### ISSUE TITLE
Unfriendly behaviour from Northern Wind Fixer toward magnificent Mara

### ISSUE THREAD

**Issue by TheSteveAllen** [SotMSteamMods/CauldronPromos#14]
Mara played Convincing Double and used Overdrive herself which, for some reason, gave her a double play at 'Pull the String'. 
On Fixer's turn, he used Tyre Iron, Dual Crowbars and Grease Monkey fist to hit a Blade Battalion. His second hit showed as being on the Baron but actually hit Mara.

**Comment by TheSteveAllen** [comment]
[log.txt](https://github.com/SotMSteamMods/CauldronPromos/files/8430220/log.txt)

**Comment by wrhyme29** [comment]
Per TheSteveAllen:
"It looks like it might be correct after all. It was the Elemental Redistributor and not the Blade Battalion. I think that I made the mistake!"

Closing issue.
